### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ljfreelancer88** [CarlGao4/Demucs-Gui#1]
Hi, I'm already using Demucs in CLI mode. Is it possible to compile this Python project of yours as single executable file for Ubuntu and Windows?

BTW, how to run this "GUI" Demucs? I'm from a Web background.

Thanks in advance

**Comment by CarlGao4** [comment]
Sorry, this project is still developing. We will try to finish it before March, 2022.

**Comment by CarlGao4** [comment]
The first beta version has been released. But the binaries will only be packed for official releases. So I will close this issue, and you can reopen it or start a new issue if you have more questions.
