### ISSUE TITLE
Just a minor suggestion

### ISSUE THREAD

**Issue by austinyen56** [CarlGao4/Demucs-Gui#10]
Hi, thanks for making demucs in a gui form. I think it will be nice if it's documented in the gui or readme on what the `split` and `overlap` values mean.

**Comment by CarlGao4** [comment]
That's a good idea! I'll add them in 0.2 when I'm available.

**Comment by CarlGao4** [comment]
Hmmmmm... I opened #23 to create the doc because I’ve no idea about where to start currently. Everybody is welcomed to help.

**Comment by CarlGao4** [comment]
I've added the doc. See [usage.md](/CarlGao4/Demucs-Gui/blob/main/usage.md)
