### ISSUE TITLE
Release executable file triggering multiple AV systems on my box.

### ISSUE THREAD

**Issue by tristansly** [CarlGao4/Demucs-Gui#13]
## Question

Ask your question here. 
![mbam_cE0wzn3lkn](https://user-images.githubusercontent.com/15840055/191247540-3c907198-90f1-4466-931d-5cb263f6e36f.png)

Malwarebytes
www.malwarebytes.com
![kMU0UXARW1](https://user-images.githubusercontent.com/15840055/191247822-44e80b30-8cf6-47e2-98ba-2eedb70d0057.png)

-Log Details-
Scan Date: 9/20/22
Scan Time: 4:21 AM
Log File: 6c749324-38d6-11ed-b85b-001986001e8b.json

-Software Information-
Version: 4.5.14.210
Components Version: 1.0.1751
Update Package Version: 1.0.60039
License: Trial

-System Information-
OS: Windows 10 (Build 19044.2006)
CPU: x64
File System: NTFS
User: ech0-V\ech0-V

-Scan Summary-
Scan Type: Custom Scan
Scan Initiated By: Manual
Result: Completed
Objects Scanned: 1
Threats Detected: 1
Threats Quarantined: 0
Time Elapsed: 1 min, 11 sec

-Scan Options-
Memory: Disabled
Startup: Disabled
Filesystem: Enabled
Archives: Enabled
Rootkits: Disabled
Heuristics: Enabled
PUP: Detect
PUM: Detect

-Scan Details-
Process: 0
(No malicious items detected)

Module: 0
(No malicious items detected)

Registry Key: 0
(No malicious items detected)

Registry Value: 0
(No malicious items detected)

Registry Data: 0
(No malicious items detected)

Data Stream: 0
(No malicious items detected)

Folder: 0
(No malicious items detected)

File: 1
Malware.AI.3593720382, C:\PORTABLEAPPS\DEMUCS-GUI_0.1_CUDA_RELEASE_WIN_X64\DEMUCS-GUI.EXE, No Action By User, 1000000, -701246914, 1.0.60039, 6E2C3D6BE268D157D633D23E, dds, 01947385, 9517FDA161C9D507FFF161988D1EC278, 4635483BABA1E8168F6FCAF1FC42BEC3AFAE1F2F1EDBADFBA1B73A71D96E70BC

Physical Sector: 0
(No malicious items detected)

WMI: 0
(No malicious items detected)

(end)

**Comment by CarlGao4** [comment]
I'm also curious about this. I noticed that some antivirus softwares see this program as a virus, but in fact it is just a Python launcher and I'm 100% sure that it is safe. If you are familiar with fixing these problems, can you help me generate some more detailed summaries (i.e. which part of the program cause this problem and what does it do) and help me fix this?

**Comment by tristansly** [comment]
I didn't run it, my antivirus quarantined it before I could use it.
