### ISSUE TITLE
4.0 version Gui

### ISSUE THREAD

**Issue by KimHBin** [CarlGao4/Demucs-Gui#17]
When can we expect to see the GUI of version 4.0?

**Comment by CarlGao4** [comment]
As I've said in README: 
**This project is temporarily suspended, development will be resumed when the developers are available**

**Comment by CarlGao4** [comment]
If you'd like to have an exact date, I can only say that it will not earlier than June

**Comment by KimHBin** [comment]
> 

Thanks for the reply
Is the gui program you provide different from "Ultimate Vocal Remover"?

**Comment by CarlGao4** [comment]
> Is the gui program you provide different from "Ultimate Vocal Remover"?

That's true.

**Comment by CarlGao4** [comment]
Duplicate of #18
