### ISSUE TITLE
When can we expect to see the GUI of version 4.0?

### ISSUE THREAD

**Issue by KimHBin** [CarlGao4/Demucs-Gui#18]
When can we expect to see the GUI of version 4.0?

**Comment by CarlGao4** [comment]
As I've said in README: 
**This project is temporarily suspended, development will be resumed when the developers are available**

**Comment by CarlGao4** [comment]
If you'd like to have an exact date, I can only say that it will not earlier than June

**Comment by Aleskis** [comment]
Thank you for the great job ! Using Demucs each week ; also hope the integration of Demucs 4 :)

**Comment by CarlGao4** [comment]
Actually, you can now install the codes manually and install demucs 4.0.0 then you will see that v4 models are already supported.

BTW, the development of Demucs-GUI 1.0 is nearly ended, but this time I used APIs, so I need to wait for the release of demucs 4.1.0
