### ISSUE TITLE
Add mixer (two-stem separation)

### ISSUE THREAD

**Issue by CarlGao4** [CarlGao4/Demucs-Gui#25]
Add two-stem separation: This is important, I think. As of now, the program only converts using the standard 4 stems (vocals, bass, drums, other).

**Comment by cacalo** [comment]
Hello!
Maybe it would be a nice idea to remember the options marked in the mixer. In my case, I never want the drums stem and I was used to just delete it, I can now uncheck it from the mixer but I still have to do it every single time I open the tool.

**Comment by CarlGao4** [comment]
It's on my list now, the next step is to add a function to save presets

**Comment by cjhines7** [comment]
Loving the update. I'm using this to create backing tracks for guitar practice.  Just wondering if you would consider adding panning options to the mixer. It would be a great addition. Thanks

**Comment by CarlGao4** [comment]
> Just wondering if you would consider adding panning options to the mixer

Have no plan yet. Maybe you can open an issue to describe the feature and I'll think about it. It sounds like that this feature requires real-time playback and some simple audio editor functions... So maybe a "one-file mode" is required

**Comment by CarlGao4** [comment]
@cjhines7 If you still want this feature, please open another issue.

**Comment by CarlGao4** [comment]
Closing as 1.1 has been released.
