### ISSUE TITLE
Demucs-GUI_1.0a1_cuda.7z doesn't dun.

### ISSUE THREAD

**Issue by wrightwriter** [CarlGao4/Demucs-Gui#27]
### happen

Previous version used to work!
I open `Demucs-GUI.exe`, there's a terminal window for around 3-10 seconds, then it closes.

rtx 3060, ryzen 5600X, cuda toolkit (not in pip) installed, latest drivers.

Do I need to install anything else? The pip cuda stuff?

### What is the platform you are using?

Windows

**Comment by CarlGao4** [comment]
No need to install any dependency. It will open a terminal window and close itself, but after that it should show a window

**Comment by wrightwriter** [comment]
Weird, process is not in task manager. Could a wrong python.exe environment variable be the issue? I think I have the 3.9 from pip as env variable.

**Comment by CarlGao4** [comment]
No influence. Could you please provide the latest log file? You can find it under `%APPDATA\demucs-gui\log` (just press <kbd>Win</kbd>+<kbd>R</kbd> and paste it inside)

**Comment by CarlGao4** [comment]
Please run `lodctr /R` and have a try first

**Comment by wrightwriter** [comment]
```ts
Z:\Demucs-Gui-main>lodctr /R

Error: Unable to rebuild performance counter setting from system backup store, error code is 5
```

**Comment by wrightwriter** [comment]
Thank you, after a couple of `lodctr /R` runs (it failed with error first 2 times), it got fixed :)

**Comment by ebjazz93** [comment]
works like a charm. Many thanks, have a good day and a best wishes for 2024.

**Comment by DilsonAbraham** [comment]
I have the same issue with version 1.2

here is my log file.
[20241001_222135_demucs_gui_log.log](https://github.com/user-attachments/files/17215328/20241001_222135_demucs_gui_log.log)
