### ISSUE TITLE
Can't install demucs>=4.1.0a2 which hasn't been released

### ISSUE THREAD

**Issue by sveinbjornpalsson** [CarlGao4/Demucs-Gui#29]
### happen

I got an error running the pip command recommended for mac:

```
(base) sveinbjorn@svenbook-pro-3 Demucs-Gui % pip install -r requirements.txt

ERROR: Could not find a version that satisfies the requirement demucs>=4.1.0a2 (from versions: 0.0.0, 0.0.1, 0.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 4.0.0, 4.0.1)
ERROR: No matching distribution found for demucs>=4.1.0a2
```
Conda similarily can't find 4.1.0a2 of demucs (and it can't find soundfile or soxr either)

I'm such a noob that I just run verbose, I just do what the guide says. Apologies if I'm missing something obvious.
I am assuming that the a2 release has been removed? 
While not strictly neccessary, it'd be instructive if someone might tell me how I could get past this myself.

I don't know if this is technically a bug or if it's called something else. All enlightenment is welcomed.

(m1 max, MacOS Sonoma 14.0)

### What is the platform you are using?

macOS

### log

Since the app didn't install, here's the whole terminal log for this, it's all I've got.

(base) user@machine Demucs-Gui % pip install -r requirements.txt

ERROR: Could not find a version that satisfies the requirement demucs>=4.1.0a2 (from versions: 0.0.0, 0.0.1, 0.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 4.0.0, 4.0.1)
ERROR: No matching distribution found for demucs>=4.1.0a2
(base) user@machine Demucs-Gui % ls
GUI			fonts			requirements.txt
LICENSE			history.md		requirements_cuda.txt
README.md		icon			usage.md
(base) user@machine Demucs-Gui % conda install --yes --file requirements.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): / conda install --yes --file requirements.tdone
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - soundfile[version='>=0.9.0']
  - demucs[version='>=4.1.0a2']
  - soxr[version='>=0.3.6']

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by CarlGao4** [comment]
Now the requirements of develop branch have changed demucs requirement into GitHub repo
