### ISSUE TITLE
Not opening?

### ISSUE THREAD

**Issue by lucellent** [CarlGao4/Demucs-Gui#3]
Dunno what else I should do, I installed the cuda requirements and added the pretrained folder to the GUI folder. If I run GuiMain - nothing happens, the CMD box flashes for a quick second and that's it

**Comment by lucellent** [comment]
I have python 3.9.6 and regular Demucs via cmd runs just fine

**Comment by CarlGao4** [comment]
Thanks for your issue. 
I guess what happened was that you double-clicked it in the file explorer. If this, probably the content on the window is `Can't find a default Python. `
Please try this:
If you run demucs by running `python -m demucs xxx`, then please right-click in the `GUI` folder, choose `open in PowerShell` or `Open in Windows Terminal`, then activate your environment and run `python GuiMain.py`.

**Comment by CarlGao4** [comment]
> Dunno what else I should do, I installed the cuda requirements and added the pretrained folder to the GUI folder. If I run GuiMain - nothing happens, the CMD box flashes for a quick second and that's it

By the way, did you follow the instructions on PyTorch official website to install torch and cuda?

**Comment by lucellent** [comment]
Turns out the issue was that I had one missing module - psutil (I think), it now opens

One thing is - I can't find how do I change the models, I couldn't find the same model files in the original demucs folder, as I want to use mdx_extra, not the quantized version

**Comment by CarlGao4** [comment]
Sorry I forgot to add psutil to requirements_cuda.txt, and now I added it. 

To change models, please empty the entry of `Model path`, and then input the model you want to use into `Model name`, like this:
![image](https://user-images.githubusercontent.com/57826826/161224064-4f932d32-8a69-4211-8197-c2b0ae86e0c7.png)

**Comment by lucellent** [comment]
Ah, I see now

One last question - what does "Split" do? I haven't seen that command before

**Comment by CarlGao4** [comment]
Since the models will require large ammount of memory, so the tracks would be splited into shorter chunks to sav memory. `split` controls how long the trunks will be.

**Comment by lucellent** [comment]
Thanks again for explaining, everything works great so far!

I'd be up for designing a UI, but I don't know s#it about coding :D
