### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by thenormal** [CarlGao4/Demucs-Gui#4]
Hello. Good job on the pre-release program. It works for me. I have a few suggestions which I hope you will consider implementing in the future.

- [x] 1. Add mp3 support, both as input and output: Many people have mp3 files in their HDs. As of now, they are forced to convert an mp3 to a supported file (such as .flac or .wav) to import into DemucsGUI. Also, I noticed that the program only outputs .wav files. It would be great to choose which output format one wants to be returned.
- [x] #25
- [x] 3. Add options such as bitrate, float32, etc...

**Comment by CarlGao4** [comment]
Thanks for your suggestion.

**Comment by mandrixoh1** [comment]
1. Demucs-GUI_0.1_CUDA_Release_Win_x64.7z

This is the minimal pack with only CPU and mdx_extra_q model. You can simply run Demucs-GUI.exe.


2. Demucs-GUI_0.1_CPU_Release_Win_x64.7z

This is the pack with CUDA enabled and mdx_extra_q model. You can simply run Demucs-GUI.exe.

So this is confusing. The version with CUDA in the title actually does NOT use CUDA?

**Comment by CarlGao4** [comment]
Sorry I made a mistake 😅

**Comment by CarlGao4** [comment]
All done!
