### ISSUE TITLE
Usability suggestion

### ISSUE THREAD

**Issue by cacalo** [CarlGao4/Demucs-Gui#40]
I find that I prefer to use the 0.1 version to the 1.0 version because that one fits my my requirements perfectly.
Therefore, I would suggest the posibility of a "simplified UI" that you can opt in as starting view of the tool.

If this is not possible or no one ones to work on it,  it can be replaced by a few settings + recording the last used options:
Some settings I would use:
- Start separation as soon as you select a file. (Maybe a "load and start" button would work.
- Remember output encoder settings (I use wav but I have to chage it from flac every time). 

Lastly, thank you for making this. I was using the CLI before and I found an improvement using this interface.

**Comment by CarlGao4** [comment]
> Start separation as soon as you select a file. (Maybe a "load and start" button would work.

I'll Add a checkbox "start separation once added to queue"

> Remember output encoder settings

That's a good idea. I'll add it in 1.1 though I may have to migrate old config file...

**Comment by cacalo** [comment]
It works perfect!
Thank you for your commitment!
