### ISSUE TITLE
Can't run Demucs-gui

### ISSUE THREAD

**Issue by ebjazz93** [CarlGao4/Demucs-Gui#43]
Hi, 
Thanks for this useful project. 
I'm on W10, amd gpu, python 3.10.6 installed
I have unzip and run Demucs-GUI.exe. A cmd window opens less than one second and close, so nothing happen. I tried v.1.1a and 1.2 cpu, same problem. Is there something I did wrong? some prerequisites i missed ?

**Comment by CarlGao4** [comment]
Is there any log file? (you can open it from `C:\Users\<Your Username>\AppData\Local\demucs-gui\logs`)
If not, can you run from cmd and see what it has output?

**Comment by ebjazz93** [comment]
Thanks for you concern
There is no such folder as demucs-gui in appData\local, 
I launch demucs-gui.exe from cmd here is the result
C:\Demucs-GUI_1.1a2_cpu>Demucs-GUI.exe
C:\Demucs-GUI_1.1a2_cpu>

**Comment by CarlGao4** [comment]
It's my mistake
It should be `AppData\Roaming\demucs-gui\logs`

**Comment by CarlGao4** [comment]
Same error as https://github.com/CarlGao4/Demucs-Gui/issues/27#issuecomment-1768055897 
Closing

**Comment by ebjazz93** [comment]
ok, thanks,
