### ISSUE TITLE
Demucs already installed

### ISSUE THREAD

**Issue by curryarts** [CarlGao4/Demucs-Gui#5]
I have Demucs 3 installed and operating using the command line in Anaconda prompt. I would just like to install the GUI without reinstalling Demucs. Is that possible? I don't want to hose up my current CPU only installation.

**Comment by CarlGao4** [comment]
Only beta versions was released so no packed environment was available. Directly running the script requires Demucs manually installed, so you needn't to reinstall Demucs.
