### ISSUE TITLE
Bug: Save Path keeps being altered from the default to a previously saved file

### ISSUE THREAD

**Issue by djaychela** [CarlGao4/Demucs-Gui#52]
### happen

1. Open DemucsGUI and pick a file to split, and complete the process.
2. Restart the program and select another model (or the original).  The Save Path is now the path of one of theprevious stems:

![image](https://github.com/CarlGao4/Demucs-Gui/assets/2767094/ada784f7-df06-406d-82b0-61d1b8b82ae4)

Each time I have to manually set it back to the default of `separated/{model}/{track}/{stem}.{ext}` (Which is at the bottom of the list).

### What is the platform you are using?

Windows

**Comment by CarlGao4** [comment]
I noticed this bug which is introduced in 1.1b1

**Comment by djaychela** [comment]
Just tested it on macOS and it's the same there as well.

**Comment by CarlGao4** [comment]
[clear_location_history.zip](https://github.com/CarlGao4/Demucs-Gui/files/14613146/clear_location_history.zip)
Currently you can run this to clear all location history after exiting Demucs GUI

**Comment by VinneyUK** [comment]
> Will you be doing a new build with the fix done? Only asking as I've done a video featuring this in a stem-splitting shootout, and am doing one this week specifically on Demucs-GUI... and hopefully it will get you some more donations for model training. Really love this - performs as well as Spectralayers 10 and RipX DAW in my testing, and it's MUCH faster.

Spectrlayers and RipX can't touch this.

**Comment by CarlGao4** [comment]
Fixed in 1.1
