### ISSUE TITLE
Accelerate with AMD instructions should require using git

### ISSUE THREAD

**Issue by matthew-a-dunlap** [CarlGao4/Demucs-Gui#57]
### Issue

Now that 1.1 requires getting submodules with git, the instructions there that say you can download the zip do not work. These instructions are not present in the other install paths, so I think it should be removed here.

This looks to also be a problem with the intel instructions.

I'm new to using this (awesome) project, but could do a text change PR if needed :)

### What is the platform you are using?

Linux

**Comment by CarlGao4** [comment]
You can open a PR :smile:

**Comment by CarlGao4** [comment]
Actually, you can just install torch 2.2.0 after installing demucs as demucs can only use torchaudio no greater than 2.1.0
However Demucs-Gui doesn't use torchaudio, so you can just install torch 2.2.0 and torchaudio 2.2.0 and start this program
