### ISSUE TITLE
A bug regarding overlap/shifts?

### ISSUE THREAD

**Issue by lucellent** [CarlGao4/Demucs-Gui#6]
I was trying to Demucs a very short song (like 30 seconds) and I believe my PC specs are more than enough to handle it (3070, 64GB RAM)

So I set the overlap to 0.60 and shifts to the maximum 20 for the sake of it, but when I ran the conversion it outputted silent tracks. So I lowered the values and ended up at overlap 0.30 and shifts 10 where it started actually working (dunno if that's the maximum, haven't experimented a lot) but I guess those values are still too much since the "others" stem was too thinned out (it didn't have much sound compared to the one with default values)

Also a side thing, would be nice if we could just use our keyboard to type out the numbers, currently it looks like it's not supported?

**Comment by CarlGao4** [comment]
Please download the latest codes and upload the logs here.
