### ISSUE TITLE
Allowing retry saving output audio when saving failed

### ISSUE THREAD

**Issue by CarlGao4** [CarlGao4/Demucs-Gui#60]
If an output write failed, the whole separation would be performed again, which is very time-consuming. Add an option to pause the separation process immediately when writing fails so user can change writing parameters and try saving again and again.

**Comment by charliemarshall1996** [comment]
Hello,

I think I'll give this a go, if that's ok? 
Is there a contribution doc on the repo - just want to keep within standards!

**Comment by CarlGao4** [comment]
That's great news that you'd like to contribute!
Actually, I didn't create a contribution doc - just run the black formatter before committing (with argument `-l 120`)
Sorry for making the codes such a mess as I made so few comments...

**Comment by CarlGao4** [comment]
@charliemarshall1996 Are you still working on this?

**Comment by charliemarshall1996** [comment]
Hi!

Apologies, just been made redundant so my attention is elsewhere. If need
be, please pass this off to someone else.

**Comment by CarlGao4** [comment]
Never mind, I'll do it myself
