### ISSUE TITLE
Bug: (the bug you found) :  Program hangs at launch on splashscreen 

### ISSUE THREAD

**Issue by ghramsey** [CarlGao4/Demucs-Gui#61]
### happen

This is for version 1.2b1 
The program opens and closes a dos box pop up window at launch.
Splashscreen shows "starting..." and never continues.
GPU is a ZOTAC branded RTX3060 12GB 
Windows 10 Home.
It was working on the previous release

### What is the platform you are using?

Windows

### log

```true
[20240511_222925_demucs_gui_log.log](https://github.com/CarlGao4/Demucs-Gui/files/15286745/20240511_222925_demucs_gui_log.log)
e.
```

**Comment by CarlGao4** [comment]
I'm not sure about what happened without a log file.
Maybe you can try running the program from a terminal?

**Comment by shotfirer** [comment]
I caught the same glitch once, and had to kill the process with the task manager. I'm attaching the log from that launch
[20240512_144742_demucs_gui_log.log](https://github.com/CarlGao4/Demucs-Gui/files/15286130/20240512_144742_demucs_gui_log.log)

**Comment by ghramsey** [comment]
Where does the program create log files?   It was not located in the runtime folder.

If it goes in appdata somewhere it's possible still there. 
I've reverted to using the 1.2a1 version and that is working.

**Comment by CarlGao4** [comment]
`%appdata%\demucs-gui\logs`

**Comment by ghramsey** [comment]
OK.  I got the logs.  I added one to the ticket.

**Comment by CarlGao4** [comment]
Please try the latest 1.2b2

**Comment by CarlGao4** [comment]
If this issue has been fixed, please close this issue.
