### ISSUE TITLE
Cannot start Demucs-Gui - stuck at "Loading modules..."

### ISSUE THREAD

**Issue by K3nn3th2** [CarlGao4/Demucs-Gui#7]
Hey, 

I tried to run Demucs-gui with python 3.10 and python 3.9.
in both cases it gets stuck at the "Loading Modules..." splash screen.

any ideas how to get it working?

thanks!

**Comment by CarlGao4** [comment]
Sorry that I can’t tell you what to do because logging have not been supported in *0.1a1*. I will add it into *0.1a2*, and please upload the log file then so I can tell what happened. 
I’m in UTC+0800 time zone so I’m about to sleep. I will notify you as soon as *0.1a2* is available.

**Comment by CarlGao4** [comment]
Now binaries are available.
