### ISSUE TITLE
demucs-gui Failed to initialize log file. 

### ISSUE THREAD

**Issue by oysteinllunde** [CarlGao4/Demucs-Gui#75]
can somebody help me sort this out ? need it for some music and i really enjoyed using it while it worked.

**Comment by CarlGao4** [comment]
I can't help with this error currently. Please provide your information about your system and where you put the program.

**Comment by CarlGao4** [comment]
@oysteinllunde I'll close this issue if there are no more replies in a week

**Comment by jg-33** [comment]
Hi, I'm also experiencing this issue with Demucs-GUI_1.2_macOS_ARM64.dmg on an apple silicon with macOS 14.6.1. I have python 3.11.7 installed. The program is in Macintosh HD>Applications. Any help would be appreciated - thanks!

**Comment by oysteinllunde** [comment]
I completely reinstalled macos fixed it! It might be updates from mac causing it no idea… hope this helps but not a fix! Also same newest updates sonoma macbook pro m3 14

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
