### ISSUE TITLE
How to disable Demucs rescaling the volume of stems after extraction?

### ISSUE THREAD

**Issue by DJTonydacoder** [CarlGao4/Demucs-Gui#77]
[https://github.com/facebookresearch/demucs#:~:text=It%20can%20happen,it%20to%20Demucs.](url)
I find it annoying that Demucs would reduce the stems' volume after they're extracted. 
Is there anyway to disable Demucs rescaling the volume of the split stems without reducing the volume of the input mixture and passing  --clip-mode clamp (cuz I don't want hard-clipping on my 32-bit wav files)?
![Screenshot 2024-06-26 132037](https://github.com/facebookresearch/demucs/assets/155869487/a404a496-5b7a-4dd6-ba19-3a4bc6ccf83b)

**Comment by CarlGao4** [comment]
You can change sample format to float32 and set clip mode to none
In demucs command line tool, you can add `--float32 --clip-mode none` arguments

**Comment by DJTonydacoder** [comment]
> You can change sample format to float32 and set clip mode to none In demucs command line tool, you can add `--float32 --clip-mode none` arguments

Thanks, but how do you do it in the Google Colab?

**Comment by CarlGao4** [comment]
This repo is no longer maintained 
Use this instead 
```bash
python3 -m pip install -U git+https://github.com/adefossez/demucs#egg=demucs
```

**Comment by DJTonydacoder** [comment]
> This repo is no longer maintained Use this instead
> 
> ```shell
> python3 -m pip install -U git+https://github.com/adefossez/demucs#egg=demucs
> ```

I ran the `python.exe -m pip install -U git+https://github.com/adefossez/demucs#egg=demucs` and got this error message
![Screenshot 2024-06-29 145202](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/f3c82a79-aae9-4cfe-a313-fc6482e65ffe)

Also, you still didn't give me a working solution to this stupid `--clip mode` issue
![Screenshot 2024-06-28 184930](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/6ccd6512-e001-4e59-9903-00b4ed6cc54d)

**Comment by CarlGao4** [comment]
Just install the one in the new repo and `--clip-mode none` will be available
