### ISSUE TITLE
Some weird error message when installing the bleeding edge of Demucs

### ISSUE THREAD

**Issue by DJTonydacoder** [CarlGao4/Demucs-Gui#78]
I tried installing the bleeding edge version of Demucs, I followed all of [adefossez's instructions](https://github.com/adefossez/demucs/blob/main/docs/windows.md).

When I ran the command `python.exe -m pip install -U git+https://github.com/facebookresearch/demucs#egg=demucs`, I got this message:
![Screenshot 2024-06-27 120054](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/a890d5a8-00d6-4439-89b2-aa2030963c56)

What does that mean? Did I do something wrong?

**Comment by CarlGao4** [comment]
Just use Demucs GUI if you are new to coding

**Comment by DJTonydacoder** [comment]
> Just use Demucs GUI if you are new to coding

1. I know how to use Demucs through the Anaconda prompt, I'm trying to install the bleeding edge of Demucs through the `python.exe -m pip install -U git+https://github.com/facebookresearch/demucs#egg=demucs` and got the error message: "**The system cannot find the file specified executing command git version. Cannot find command 'git' - do you have 'git' installed and in your PATH**". I need you to send me a video on how to fix this issue.
2. You still haven't given me a working solution to the `--clip mode issue`, all I got was the message saying there's only to options for `--clip mode`: `clamp` and `rescale`.
3. Does Demucs GUI use the bleeding edge of Demucs installed with `python.exe -m pip install -U git+https://github.com/facebookresearch/demucs#egg=demucs` or just the standard version installed with `python.exe -m pip install -U demucs`?

**Comment by CarlGao4** [comment]
Yes, Demucs GUI requires some latest features, so it **must** install the latest git version
You need to install git for windows if you want to install the latest version
Please run `pip install -U git+https://github.com/adefossez/demucs.git` to use `--clip-mode none`

**Comment by DJTonydacoder** [comment]
> Yes, Demucs GUI requires some latest features, so it **must** install the latest git version You need to install git for windows if you want to install the latest version Please run `pip install -U git+https://github.com/adefossez/demucs.git` to use `--clip-mode none`

I did everything you suggested...
I followed all of [adefossez's instructions](https://github.com/adefossez/demucs/blob/main/docs/windows.md), I downloaded the [latest git version for Windows](https://github.com/git-for-windows/git/releases/download/v2.45.2.windows.1/Git-2.45.2-64-bit.exe), I ran both `pip install -U git+https://github.com/adefossez/demucs.git` and `pip install -U git+https://github.com/adefossez/demucs#egg=demucs`, and still got the same error message:
<blockquote class="imgur-embed-pub" lang="en" data-id="a/qSJvykm"  ><a href="//imgur.com/a/qSJvykm">Stupid Demucs error</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by CarlGao4** [comment]
Maybe just restart the computer?
If it still doesn't work, you can just download zip and extract it and switch to this directory and run `pip install -U --force-reinstall .`

**Comment by DJTonydacoder** [comment]
> Maybe just restart the computer? If it still doesn't work, you can just download zip and extract it and switch to this directory and run `pip install -U --force-reinstall .`

![Screenshot 2024-06-29 160842](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/9d19a9c2-a2b5-4b9a-821b-d545ce7c0643)

**Comment by CarlGao4** [comment]
You need to download zip first on https://github.com/adefossez/demucs
Extract it and switch to this directory
Then run `pip install -U --force-reinstall .`
You've lost the trailing dot in your last command

**Comment by DJTonydacoder** [comment]
> You need to download zip first on https://github.com/adefossez/demucs Extract it and switch to this directory Then run `pip install -U --force-reinstall .` You've lost the trailing dot in your last command

![Screenshot 2024-06-29 162840](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/0e28d868-211f-4b4e-91e1-650cf5b64f71)
![Screenshot 2024-06-29 162538](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/f137ef5f-a57e-42c5-963f-45825d48dd6e)
![Screenshot 2024-06-29 162554](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/83e5a7bd-ff27-42be-b178-f49aa660847c)
![Screenshot 2024-06-29 162633](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/33018bbd-24d4-4ed2-8ad8-5e4f6f8befd1)
![Screenshot 2024-06-29 162701](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/f7793d7a-0beb-4195-a284-0b19e2e09fcc)
![Screenshot 2024-06-29 162723](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/07d63caa-5e5c-473e-afcf-86033592ae64)
![Screenshot 2024-06-29 162738](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/e29a568f-2baf-443c-9b14-f10eff5bf458)
![Screenshot 2024-06-29 162802](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/5e3902d0-b724-4d2f-aeb9-ab5d3927ab82)
![Screenshot 2024-06-29 162819](https://github.com/CarlGao4/Demucs-Gui/assets/155869487/bc946891-6021-469c-9563-68bd1f3edd49)

**Comment by CarlGao4** [comment]
Please install PyTorch 2.1.2 first, following the instructions on https://pytorch.org/get-started/previous-versions/#v212

**Comment by CarlGao4** [comment]
It seems that installing demucs is quite difficult for you
I really suggest that using Demucs-GUI is a better choice for you as all its environment has been packed and has even more functions than the command line tool

**Comment by DJTonydacoder** [comment]
> It seems that installing demucs is quite difficult for you I really suggest that using Demucs-GUI is a better choice for you as all its environment has been packed and has even more functions than the command line tool

@CarlGao4 Does your GUI version of Demucs have the bleeding edge version and (most importantly) have the `--clip-mode=none` option?

**Comment by CarlGao4** [comment]
Yes

**Comment by DJTonydacoder** [comment]
> Yes

Thank you very much!!! This GUI is so much easier to use!!!

Have a good day

**Comment by CarlGao4** [comment]
Actually it has all the functions the original command line has, while a lot of new features are added at the same time
