### ISSUE TITLE
Bug: requirements.txt does not forbid numpy 2.x, but will not run unless using numpy 1.x

### ISSUE THREAD

**Issue by coolmule0** [CarlGao4/Demucs-Gui#83]
### happen

1. Cannot run with numpy>=2
2. Have a system/install environment with numpy 2.x
3. run pip install -r requirments.txt (which installs 2.1.2+cu118, incompatible with numpy 2)

Get error:
```
wav_torch = torch.from_numpy(wav).clone().transpose(0, 1)
                ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available
```

### What is the platform you are using?

Linux

**Comment by CarlGao4** [comment]
Has added `numpy<2` in latest commit
