### ISSUE TITLE
Bug: (the bug you found)

### ISSUE THREAD

**Issue by SmoothBrainApe** [CarlGao4/Demucs-Gui#86]
### happen

1. fresh install on linux mint 21.3
2. did conda env for python 3.11 => git clone => pip install -r requirements_cuda.txt => run GuiMain.py

### What is the platform you are using?

Linux

### log

```true
ModuleNotFoundError: No module named 'qt_table_checkbox.side6_table_checkbox'
```

**Comment by CarlGao4** [comment]
As I've described in the README file, You should run `git submodule update --init --recursive` after cloning this repo since 1.1a2 version.
