### ISSUE TITLE
add MVSEP Demucsv4-DnR model

### ISSUE THREAD

**Issue by 4eJIoBek1** [CarlGao4/Demucs-Gui#96]
Link - https://github.com/ZFTurbo/MVSEP-CDX23-Cinematic-Sound-Demixing

Seems like its a regular Demucsv4 model, but trained on dataset for demixing cinematic things and has 3 stems: music, vocals and sfx. Its extremely useful when remastering some video stuff and i think adding this one in this gui as a model will be fine (if it uses pure demucsv4 model and easy to implement)

**Comment by CarlGao4** [comment]
Hello, I've checked its codes and there is no need to modify this software to use its models, just download the models and follow the [instructions listed in documentation](https://github.com/CarlGao4/Demucs-Gui/blob/main/usage.md#load-custom-models).
However, if you want to use the "3 checkpoints ensemble", some more actions should be done as the three models uses the same signature. What you need to do is renaming the three checkpoints to different signatures, such as `97d170e1-a778de4a.th` to `cinematic_model1-a778de4a.th` (minus sign `-` and space cannot appear in signature) and do the same to the other two files. Then, create a yml file (like `cinematic.yml`) whose content is:
```yaml
models: ['cinematic_model1', 'cinematic_model2', 'cinematic_model3']
```
and place the three file and the yml file in the same path.
